### ISSUE TITLE
Format tab titles as APL

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#917]
### Describe the issue you are having
Per the [RIDE User Guide 8.3.1.1](https://docs.dyalog.com/latest/RIDE%20User%20Guide.pdf#page=63) "Underscored Characters in Window Captions", RIDE can (in the best case, with APL385 Unicode installed) render docked editor tab titles containing underscored names legibly but wrong:
![image](https://user-images.githubusercontent.com/10961427/193800005-1163b05d-5086-40a7-bbb5-ae41a5e20d86.png)
It should render them correctly, as this is a trivial fix:
![image](https://user-images.githubusercontent.com/10961427/193799875-be997d36-9513-4903-b1c3-fc48f5347f09.png)
ride-base.css has
```css
.lm_header .lm_tab .lm_title {
  padding: 0px 10px 2px 0px;
}
```
and should be amended to:
```css
.lm_header .lm_tab .lm_title {
  padding: 0px 10px 2px 0px;
  font-family: 'apl'
}
```
(Note that it is not trivial to fix the issue when floating windows is enabled.)

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
`)ed ⒶⒷⒸ∆⍙` then look at the editor tab title

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.5.3748
  Electron: 19.0.4
  Chrome: 102.0.5005.63
  Node: 16.14.2
  Platform: Win32
  Date: 2022-08-19 14:40:20 +0200
  Git commit: 6c723cbd2b2f29276d5c2d6728e99ab47145ac33
```
